create table if not exists restaurants
(
    id bigint generated by default as identity
        constraint restaurants_pkey
            primary key,
    name varchar(255)
);

alter table restaurants owner to postgres;

create table if not exists ingredients
(
    id bigint generated by default as identity
        constraint ingredients_pkey
            primary key,
    amount numeric(19,2),
    measure_unit varchar(255),
    name varchar(255),
    price numeric(19,2),
    restaurant_id bigint
        constraint fkspy5soghmv48ax8dqgplf290j
            references restaurants
);

alter table ingredients owner to postgres;

create table if not exists recipe_ingredients
(
    id bigint generated by default as identity
        constraint recipe_ingredients_pkey
            primary key,
    amount numeric(19,2),
    ingredient_id bigint
        constraint fkgukrw6na9f61kb8djkkuvyxy8
            references ingredients
);

alter table recipe_ingredients owner to postgres;

create table if not exists recipes
(
    id bigint generated by default as identity
        constraint recipes_pkey
            primary key,
    name varchar(255),
    restaurant_id bigint
        constraint fka572dm9npnelh20vkkmkimtqo
            references restaurants
);

alter table recipes owner to postgres;

create table if not exists dishes
(
    id bigint generated by default as identity
        constraint dishes_pkey
            primary key,
    price numeric(19,2),
    recipe_id bigint
        constraint fkjbm3ptfh2qfcbj7k50ks8pmja
            references recipes,
    restaurant_id bigint
        constraint fkpslsa9mci7gsfhwukb3mx7s6n
            references restaurants
);

alter table dishes owner to postgres;

create table if not exists recipes_recipe_ingredients
(
    recipe_id bigint not null
        constraint fkn2syjrnedc91xfapw77g0wvod
            references recipes,
    recipe_ingredients_id bigint not null
        constraint uk_q0e7urae7acyr1nox9tqttmfi
            unique
        constraint fkrk23ftdvk9ix4enti8im4c30d
            references recipe_ingredients
);

alter table recipes_recipe_ingredients owner to postgres;

create table if not exists users
(
    id bigint generated by default as identity
        constraint users_pkey
            primary key,
    first_name varchar(255),
    last_name varchar(255),
    password varchar(255),
    username varchar(255),
    restaurant_id bigint
        constraint fksd7jrkn6c8wb1y8ffbdn3krel
            references restaurants
);

alter table users owner to postgres;

create table if not exists user_role
(
    user_id bigint not null
        constraint fkj345gk1bovqvfame88rcx7yyx
            references users,
    user_role varchar(255)
);

alter table user_role owner to postgres;

